# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: UA-75649351-1
title: 꿈 많은 개발자가 되자

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 꿈 많은 개발자가 되자

description: THdev
author:
  name: Tae-hwan
  email: taehwan@thdev.tech
  github: taehwadev
  twitter: dbtek
  pinterest: asd123
  linkedin: asd123
  bio: Your stylish, minimalist theme!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# Enter your Facebook app-code
facebook_user_id: taehwan.dev
facebook_app_id: 1093577184027253

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
